#define T_EOF                            1
#define K_CLASS                          2
#define T_OSET                           3
#define T_CSET                           4
#define ID                               5
#define T_SEMICOLON                      6
#define T_COMMA                          7
#define T_OBRACKET                       8
#define INT_CONSTANT                     9
#define T_CBRACKET                      10
#define T_ASSIGN                        11
#define T_OPAR                          12
#define T_CPAR                          13
#define K_VOID                          14
#define K_INT                           15
#define K_BOOLEAN                       16
#define K_PRINT                         17
#define K_READ                          18
#define STRING_CONSTANT                 19
#define K_IF                            20
#define K_ELSE                          21
#define K_WHILE                         22
#define K_FOR                           23
#define K_RETURN                        24
#define K_BREAK                         25
#define K_CONTINUE                      26
#define BOOL_OP_OR                      27
#define BOOL_OP_AND                     28
#define REL_OP                          29
#define BIT_SHIFT_OP                    30
#define ARITH_OP_SUM                    31
#define ARITH_OP_MUL                    32
#define T_NOT                           33
#define CHAR_CONSTANT                   34
#define REAL_CONSTANT                   35
#define K_TRUE                          36
#define K_FALSE                         37
