#define TK_EOF                           1
#define KW_PRINT                         2
#define TK_SEMICOLON                     3
#define KW_ASSIGN                        4
#define TK_ID                            5
#define TK_EQUAL                         6
#define KW_IF                            7
#define TK_LPAREN                        8
#define TK_RPAREN                        9
#define TK_LSET                         10
#define TK_RSET                         11
#define KW_WHILE                        12
#define TK_TEXT                         13
#define TK_LESS                         14
#define KW_ELSE                         15
#define TK_ADD                          16
#define TK_SUB                          17
#define TK_MULT                         18
#define TK_DIV                          19
#define TK_NUM                          20
